# Python to SQL, and back again
In this codealong we will show you how to create a relational database from your pandas DataFrames.
> **To run this notebook you will need to work locally and not on colab.**

---
## 1.&nbsp; Import libraries 💾
If you haven't already installed sqlalchemy, you will need to. Uncomment the code below, install, and then recomment the code - you only need to install it once.

In [5]:
import pandas as pd
from dotenv import load_dotenv

In [6]:
load_dotenv()

True

---
## 2.&nbsp; Relational Databases 📂

Fantastic! This DataFrame will be the foundation of our authors table.

To download the sql file that we will follow for this section, [click here](https://drive.google.com/uc?export=download&id=1tln_33FM7D9wLckzxacBJNcMYqtyxybE)

If you'd like more information about MySQL data types [click here](https://www.w3schools.com/mysql/mysql_datatypes.asp).

---
## 5.&nbsp; Sending the information from this notebook to sql 📠
To establish a connection with the SQL database, we need to provide the notebook with the necessary information, which we do using the connection string below. You will need to modify only the password variable, which should match the password you set during MySQL Workbench installation.

In [2]:
df_cities = pd.read_csv("cities_df.csv")

In [41]:
from sqlalchemy import create_engine
import os

schema = "sql_workshop"          
host = "127.0.0.1"
user = "root"
password = os.getenv("MySQLPassword")
port = 3306

engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}:{port}/{schema}"
)

In [8]:
#connecting to cloud host
from sqlalchemy import create_engine
import os

schema = "sql_workshop"          
host = "34.53.185.249"
user = "root"
password = os.getenv("MySQLPassword")
port = 3306

engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}:{port}/{schema}"
)

In [42]:
import pandas as pd
from sqlalchemy import create_engine
import os

# 1. Setup Connection (using your GCP Public IP)
def create_engine_cloud():
    host = "34.53.185.249"
    user = "root"
    password = os.getenv("MySQLPassword")
    schema = "sql_workshop" 
    port = 3306

    engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{schema}")
    return engine

# 2. Match the DataFrame to the SQL Schema
# We rename 'City' to 'city_name' and ensure all other names are lowercase

df_cities.rename(columns={
    "City": "city_name",
    "Country": "country",
    "Latitude": "latitude",
    "Longitude": "longitude"
}, inplace=True)

# 3. Ensure Data Types match the SQL FLOAT requirement
df_cities["latitude"] = pd.to_numeric(df_cities["latitude"], errors='coerce')
df_cities["longitude"] = pd.to_numeric(df_cities["longitude"], errors='coerce')

# 4. Export to Cloud
try:
    df_cities.to_sql(
        name="city", 
        con=engine, 
        if_exists="append", # Adds to the table without deleting the schema
        index=False         # Prevents pandas from trying to upload its own index
    )
    print("Success! Data exported to GCP.")
except Exception as e:
    print(f"Error: {e}")

Success! Data exported to GCP.

In [10]:
df_population = pd.read_csv("population_data.csv")

In [11]:
df_population.rename(
    columns={
        "City": "city_name",
        "Population": "population"
    },
    inplace=True
)

In [12]:
df_population["year_data"] = pd.to_datetime(
    df_population["population"], dayfirst=True
).dt.year.astype(int)

In [13]:
df_population.to_sql(
    "population",
    con=engine,
    if_exists="replace",  # replaces old table
    index=False
)

3

In [18]:
import requests

country = "DE"
city = "Berlin"
API_key = os.getenv("API")

url = "https://api.openweathermap.org/geo/1.0/direct"

params = {
    "q": f"{city},{country}",
    "limit": 1,
    "appid": API_key
}

response = requests.get(url, params=params)
city_json = response.json()

city_json

[{'name': 'Berlin',
  'local_names': {'iu': 'ᐱᕐᓖᓐ',
   'fy': 'Berlyn',
   'uz': 'Berlin',
   'eo': 'Berlino',
   'ro': 'Berlin',
   'fa': 'برلین',
   'eu': 'Berlin',
   'kw': 'Berlin',
   'de': 'Berlin',
   'jv': 'Berlin',
   'uk': 'Берлін',
   'yi': 'בערלין',
   'ug': 'Bérlin',
   'kv': 'Берлин',
   'el': 'Βερολίνο',
   'sr': 'Берлин',
   'cy': 'Berlin',
   'pl': 'Berlin',
   'et': 'Berliin',
   'oc': 'Berlin',
   'ie': 'Berlin',
   'br': 'Berlin',
   'bi': 'Berlin',
   'fr': 'Berlin',
   'zh': '柏林',
   'ka': 'ბერლინი',
   'io': 'Berlin',
   'ja': 'ベルリン',
   'yo': 'Berlin',
   'wo': 'Berlin',
   'ru': 'Берлин',
   'bg': 'Берлин',
   'it': 'Berlino',
   'gv': 'Berleen',
   'tr': 'Berlin',
   'co': 'Berlinu',
   'lg': 'Berlin',
   'ko': '베를린',
   'su': 'Berliini',
   'my': 'ဘာလင်မြို့',
   'am': 'በርሊን',
   'fo': 'Berlin',
   'lv': 'Berlīne',
   'ky': 'Берлин',
   'tg': 'Берлин',
   'hr': 'Berlin',
   'an': 'Berlín',
   'ur': 'برلن',
   'sq': 'Berlini',
   'ps': 'برلين',
   'cs': 'Berlín',
   'rm': 'Berlin',
   'ca': 'Berlín',
   'ar': 'برلين',
   'hu': 'Berlin',
   'cu': 'Берлинъ',
   'ba': 'Берлин',
   'lb': 'Berlin',
   'cv': 'Берлин',
   'be': 'Берлін',
   'az': 'Berlin',
   'so': 'Berlin',
   'bo': 'པེ་ལིང་',
   'no': 'Berlin',
   'lt': 'Berlynas',
   'mg': 'Berlin',
   'tt': 'Берлин',
   'si': 'බර්ලිනය',
   'zu': 'Berlin',
   'mn': 'Берлин',
   'na': 'Berlin',
   'hi': 'बर्लिन',
   'ab': 'Берлин',
   'es': 'Berlín',
   'ga': 'Beirlín',
   'tl': 'Berlin',
   'ht': 'Bèlen',
   'mr': 'बर्लिन',
   'ml': 'ബെര്\u200dലിന്',
   'mt': 'Berlin',
   'ln': 'Berlin',
   'hy': 'Բեռլին',
   'kk': 'Берлин',
   'ta': 'பெர்லின்',
   'sc': 'Berlinu',
   'ms': 'Berlin',
   'qu': 'Berlin',
   'pt': 'Berlim',
   'sk': 'Berlín',
   'li': 'Berlien',
   'vi': 'Berlin',
   'da': 'Berlin',
   'mk': 'Берлин',
   'ia': 'Berlin',
   'en': 'Berlin',
   'sw': 'Berlin',
   'la': 'Berolinum',
   'af': 'Berlyn',
   'he': 'ברלין',
   'ty': 'Berlin',
   'gl': 'Berlín',
   'bn': 'বার্লিন',
   'nn': 'Berlin',
   'ku': 'Berlîn',
   'bs': 'Berlin',
   'id': 'Berlin',
   'th': 'เบอร์ลิน',
   'fi': 'Berliini',
   'gn': 'Berlin',
   'sv': 'Berlin',
   'mi': 'Pearīni',
   'nl': 'Berlijn',
   'gd': 'Berlin',
   'sh': 'Berlin',
   'is': 'Berlín',
   'sl': 'Berlin',
   'kn': 'ಬೆರ್ಲಿನ್',
   'se': 'Berlin',
   'os': 'Берлин',
   'te': 'బెర్లిన్'},
  'lat': 52.5170365,
  'lon': 13.3888599,
  'country': 'DE'}]

In [20]:
import requests

country = "DE"
city = "Berlin"
API_key = os.getenv("API")

# Reference the parameters in the URL
city_request = requests.get(
    f"https://api.openweathermap.org/geo/1.0/direct?q={city},{country}&limit=1&appid={API_key}"
)

# Convert response to JSON
city_json = city_request.json()

# Print the result
print(city_json)

[{'name': 'Berlin', 'local_names': {'hi': 'बर्लिन', 'bn': 'বার্লিন', 'af': 'Berlyn', 'se': 'Berlin', 'an': 'Berlín', 'oc': 'Berlin', 'ba': 'Берлин', 'pt': 'Berlim', 'kv': 'Берлин', 'qu': 'Berlin', 'ca': 'Berlín', 'kw': 'Berlin', 'ia': 'Berlin', 'ko': '베를린', 'cu': 'Берлинъ', 'sl': 'Berlin', 'id': 'Berlin', 'sk': 'Berlín', 'so': 'Berlin', 'bg': 'Берлин', 'cv': 'Берлин', 'os': 'Берлин', 'sv': 'Berlin', 'tt': 'Берлин', 'mk': 'Берлин', 'br': 'Berlin', 'li': 'Berlien', 'ka': 'ბერლინი', 'lb': 'Berlin', 'wo': 'Berlin', 'it': 'Berlino', 'lt': 'Berlynas', 'mr': 'बर्लिन', 'ht': 'Bèlen', 'ky': 'Берлин', 'fa': 'برلین', 'fy': 'Berlyn', 'ar': 'برلين', 'ku': 'Berlîn', 'ab': 'Берлин', 'my': 'ဘာလင်မြို့', 'nn': 'Berlin', 'he': 'ברלין', 'da': 'Berlin', 'sr': 'Берлин', 'ta': 'பெர்லின்', 'sh': 'Berlin', 'ie': 'Berlin', 'eu': 'Berlin', 'gn': 'Berlin', 'eo': 'Berlino', 'hy': 'Բեռլին', 'mg': 'Berlin', 'pl': 'Berlin', 'bi': 'Berlin', 'tg': 'Берлин', 'gl': 'Berlín', 'io': 'Berlin', 'la': 'Berolinum', 'ml': 'ബെര്\u200dലിന്', 'el': 'Βερολίνο', 'sw': 'Berlin', 'ro': 'Berlin', 'zu': 'Berlin', 'mn': 'Берлин', 'na': 'Berlin', 'yo': 'Berlin', 'jv': 'Berlin', 'sq': 'Berlini', 'ga': 'Beirlín', 'es': 'Berlín', 'si': 'බර්ලිනය', 'am': 'በርሊን', 'gd': 'Berlin', 'zh': '柏林', 'lg': 'Berlin', 'hr': 'Berlin', 'vi': 'Berlin', 'mt': 'Berlin', 'az': 'Berlin', 'en': 'Berlin', 'ms': 'Berlin', 'no': 'Berlin', 'ty': 'Berlin', 'iu': 'ᐱᕐᓖᓐ', 'rm': 'Berlin', 'tr': 'Berlin', 'th': 'เบอร์ลิน', 'fr': 'Berlin', 'be': 'Берлін', 'is': 'Berlín', 'kk': 'Берлин', 'fo': 'Berlin', 'bs': 'Berlin', 'fi': 'Berliini', 'cs': 'Berlín', 'ug': 'Bérlin', 'tl': 'Berlin', 'uk': 'Берлін', 'yi': 'בערלין', 'nl': 'Berlijn', 'sc': 'Berlinu', 'ln': 'Berlin', 'ps': 'برلين', 'lv': 'Berlīne', 'et': 'Berliin', 'ja': 'ベルリン', 'su': 'Berliini', 'de': 'Berlin', 'mi': 'Pearīni', 'gv': 'Berleen', 'kn': 'ಬೆರ್ಲಿನ್', 'bo': 'པེ་ལིང་', 'ur': 'برلن', 'uz': 'Berlin', 'hu': 'Berlin', 'cy': 'Berlin', 'ru': 'Берлин', 'te': 'బెర్లిన్', 'co': 'Berlinu'}, 'lat': 52.5170365, 'lon': 13.3888599, 'country': 'DE'}]

In [12]:
lat = city_json[0]["lat"]
lon = city_json[0]["lon"]

print(lat, lon)

52.5170365 13.3888599

In [11]:
city_data = city_json[0]
name = city_data["name"]
lat = city_data["lat"]
lon = city_data["lon"]
country = city_data["country"]

print(f"{name}, {country} → lat: {lat}, lon: {lon}")

Berlin, DE → lat: 52.5170365, lon: 13.3888599

In [12]:
import pandas as pd

# Use the already extracted variables
data = [{
    "name": name,
    "lat": lat,
    "lon": lon,
    "country": country
}]

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame
print(df)

     name        lat       lon country
0  Berlin  52.517037  13.38886      DE

In [15]:
import requests

API_key = os.getenv("API")  # copy exactly
url = "https://api.openweathermap.org/data/2.5/weather"
params = {"q": "Berlin,DE", "appid": API_key}

response = requests.get(url, params=params)
print(response.status_code)
print(response.json())

200
{'coord': {'lon': 13.4105, 'lat': 52.5244}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 287.17, 'feels_like': 286.64, 'temp_min': 285.85, 'temp_max': 288.79, 'pressure': 1019, 'humidity': 77, 'sea_level': 1019, 'grnd_level': 1013}, 'visibility': 10000, 'wind': {'speed': 3.6, 'deg': 200}, 'clouds': {'all': 0}, 'dt': 1772188075, 'sys': {'type': 2, 'id': 2000002, 'country': 'DE', 'sunrise': 1772171881, 'sunset': 1772210434}, 'timezone': 3600, 'id': 2950159, 'name': 'Berlin', 'cod': 200}

In [16]:
weather_json = {
    "coord": {"lon": 13.4105, "lat": 52.5244},
    "weather": [{"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}],
    "main": {"temp": 270.69, "feels_like": 266.57, "temp_min": 268.7, "temp_max": 272.01,
             "pressure": 1026, "humidity": 82, "sea_level": 1026, "grnd_level": 1020},
    "wind": {"speed": 3.13, "deg": 141, "gust": 5.81},
    "name": "Berlin",
    "cod": 200
}

In [21]:
import pandas as pd

# Already have city info
city_data = city_json[0]
name = city_data["name"]
lat = city_data["lat"]
lon = city_data["lon"]
country = city_data["country"]

# Weather info
temperature = weather_json["main"]["temp"]
feels_like = weather_json["main"]["feels_like"]
description = weather_json["weather"][0]["description"]
humidity = weather_json["main"]["humidity"]
wind_speed = weather_json["wind"]["speed"]

# Combine into a dictionary
data = [{
    "name": name,
    "country": country,
    "lat": lat,
    "lon": lon,
    "temp": temperature,
    "feels_like": feels_like,
    "weather": description,
    "humidity": humidity,
    "wind_speed": wind_speed
}]

# Create DataFrame
df = pd.DataFrame(data)

# Display
print(df)

     name country        lat       lon    temp  feels_like    weather  \
0  Berlin      DE  52.517037  13.38886  270.69      266.57  clear sky

   humidity  wind_speed
0        82        3.13

In [29]:
#Connection string very useful
def create_engine():
    host = "34.53.185.249"
    user = "root"
    password = os.getenv("MySQLPassword")
    schema = "sql_workshop" 
    port = 3306

    engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{schema}")
    return engine

In [30]:
#we wanna read from sql
def get_cities(engine):    
    cities_df= pd.read_sql("city", con= engine)
    cities_list= cities_df["city_name"].to_list()
    return cities_list

In [24]:
import requests
import pandas as pd

def get_weather_dataframe(cities):
    """
    Fetches location and current weather for multiple cities and returns a DataFrame.

    Parameters:
    - cities: list of city names (strings)
    - country: country code (default "DE")
    - API_key: your OpenWeather API key

    Returns:
    - pd.DataFrame with columns: name, country, lat, lon, temp, feels_like, weather, humidity, wind_speed
    """
    data = []

    for city in cities:
        # 1️Geocoding: get lat/lon
        geo_url = "https://api.openweathermap.org/geo/1.0/direct"
        API_key_geo=os.getenv("API")
        geo_params = {"q": f"{city},{country}", "limit": 1, "appid": API_key_geo}
        geo_response = requests.get(geo_url, params=geo_params)
        geo_json = geo_response.json()

        if isinstance(geo_json, list) and len(geo_json) > 0:
            city_data = geo_json[0]
            lat = city_data["lat"]
            lon = city_data["lon"]
        else:
            print(f"Geocoding failed for {city}: {geo_json}")
            continue  # skip to next city

        # 2️Weather: get current weather
        weather_url = "https://api.openweathermap.org/data/2.5/weather"
        API_key_weather=os.getenv("API")
        weather_params = {"lat": lat, "lon": lon, "appid": API_key_weather, "units": "metric"}
        weather_response = requests.get(weather_url, params=weather_params)
        weather_json = weather_response.json()

        if weather_response.status_code == 200 and "main" in weather_json:
            temperature = weather_json["main"]["temp"]
            feels_like = weather_json["main"]["feels_like"]
            description = weather_json["weather"][0]["description"]
            humidity = weather_json["main"]["humidity"]
            wind_speed = weather_json["wind"]["speed"]

            # Append to data list
            data.append({
                "name": city,
                "country": country,
                "lat": lat,
                "lon": lon,
                "temp": temperature,
                "feels_like": feels_like,
                "weather": description,
                "humidity": humidity,
                "wind_speed": wind_speed
            })
        else:
            print(f"Weather fetch failed for {city}: {weather_json}")

    # 3️Build DataFrame
    df = pd.DataFrame(data)
    return df

# Example usage
cities = ["Berlin", "Hamburg", "Cologne"]
weather_df = get_weather_dataframe(cities)
print(weather_df)

      name country        lat        lon   temp  feels_like     weather  \
0   Berlin      DE  52.517037  13.388860  15.39       14.97   clear sky
1  Hamburg      DE  53.550341  10.000654  13.98       13.34  few clouds
2  Cologne      DE  50.938361   6.959974  16.19       15.74   clear sky

   humidity  wind_speed
0        76        4.12
1        73        7.20
2        72        4.12

In [ ]:

#Overall aim is to Push data to cloud but bit seems we need some cleaning first


# 1. Clean up the DataFrame to match SQL exactly
weather_df_final = weather_df.rename(columns={
    "name": "city_name",
    "lat": "latitude",
    "lon": "longitude"
})

# 2. Add the timestamp (if not already there)
from datetime import datetime
weather_df_final["weather_timestamp"] = datetime.now()

# 3. Ensure city_id is handled
# If you haven't mapped city_ids yet, we set it to None so MySQL can handle it 
# or you can fill it if you have the IDs ready.
if "city_id" not in weather_df_final.columns:
    weather_df_final["city_id"] = None

# 4. Clear any "stuck" transactions before starting
from sqlalchemy import text
with engine.connect() as conn:
    conn.rollback()

# 5. Push to Cloud
try:
    weather_df_final.to_sql(
        "weather", 
        con=engine, 
        if_exists="append", # Use append to respect your AUTO_INCREMENT weather_id
        index=False
    )
    print("Cloud Update Successful!")
except Exception as e:
    print(f"Export failed: {e}")

Cloud Update Successful!

In [39]:
#We turn the above into a function
def push_weather_to_cloud(df, engine):
    # 1. Clean up the DataFrame to match SQL exactly
    df = df.rename(columns={
        "name": "city_name",
        "lat": "latitude",
        "lon": "longitude"
    })

    # 2. Add the timestamp (if not already there)
    from datetime import datetime
    df["weather_timestamp"] = datetime.now()

    # 3. Ensure city_id is handled
    # If you haven't mapped city_ids yet, we set it to None so MySQL can handle it 
    # or you can fill it if you have the IDs ready.
    if "city_id" not in df.columns:
        df["city_id"] = None

    # 5. Push to Cloud
    try:
        df.to_sql(
            "weather", 
            con=engine, 
            if_exists="append", # Use append to respect your AUTO_INCREMENT weather_id
            index=False
        )
        return("Cloud Update Successful!")
    except Exception as e:
        return(f"Export failed: {e}")

In [43]:
engine = create_engine_cloud()
cities = get_cities(engine)
weather_df = get_weather_dataframe(cities)
push_weather_to_cloud(weather_df, engine)

'Cloud Update Successful!'

In [19]:
weather_df = weather_df.rename(columns={
    "name": "city_name",
    "lat": "latitude",
    "lon": "longitude"
})

In [20]:
weather_df = weather_df[
    [
        "city_name",
        "country",
        "latitude",
        "longitude",
        "temp",
        "feels_like",
        "weather",
        "humidity",
        "wind_speed",
        "weather_timestamp"
    ]
]

In [18]:
from datetime import datetime

weather_df["weather_timestamp"] = datetime.now()

In [21]:
weather_df.to_sql(
    name="weather",
    con=engine,
    if_exists="append",
    index=False
)

3

In [17]:
from dotenv import load_dotenv
import os
load_dotenv()  # Load .env into environment

True

In [23]:
import requests
import os

url = "https://aerodatabox.p.rapidapi.com/flights/airports/iata/CGN"

params = {
    "offsetMinutes": -120,
    "durationMinutes": 720,
    "withLeg": "true",
    "direction": "Arrival",
    "withCancelled": "true",
    "withCodeshared": "true",
    "withCargo": "false",
    "withPrivate": "false",
    "withLocation": "false"
}

headers = {
    "X-RapidAPI-Key": os.getenv("FlightsAPI"),
    "X-RapidAPI-Host": "aerodatabox.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=params)
response.raise_for_status()

data = response.json()
data

{'arrivals': [{'departure': {'airport': {'icao': 'LOWW',
     'iata': 'VIE',
     'name': 'Vienna',
     'countryCode': 'at',
     'timeZone': 'Europe/Vienna'},
    'scheduledTime': {'utc': '2026-02-24 13:00Z',
     'local': '2026-02-24 14:00+01:00'},
    'revisedTime': {'utc': '2026-02-24 13:02Z',
     'local': '2026-02-24 14:02+01:00'},
    'runwayTime': {'utc': '2026-02-24 13:03Z',
     'local': '2026-02-24 14:03+01:00'},
    'terminal': '1',
    'checkInDesk': '151-162',
    'gate': 'C36',
    'runway': '34',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 14:30Z',
     'local': '2026-02-24 15:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 14:25Z',
     'local': '2026-02-24 15:25+01:00'},
    'terminal': '2',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'FR 9480',
   'callSign': 'RYR51NQ',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-HAW', 'modeS': '4CA95E', 'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'GCLP',
     'iata': 'LPA',
     'name': 'Gran Canaria Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'scheduledTime': {'utc': '2026-02-24 10:40Z',
     'local': '2026-02-24 10:40+00:00'},
    'revisedTime': {'utc': '2026-02-24 10:40Z',
     'local': '2026-02-24 10:40+00:00'},
    'terminal': '1',
    'checkInDesk': '315-317',
    'gate': 'C22',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:10Z',
     'local': '2026-02-24 16:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 14:58Z',
     'local': '2026-02-24 15:58+01:00'},
    'terminal': '2',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'XR 524',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 737-800'},
   'airline': {'name': 'Corendon  Europe', 'iata': 'XR', 'icao': 'CXI'}},
  {'departure': {'airport': {'name': 'Unknown'}, 'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:00Z',
     'local': '2026-02-24 16:00+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:06Z',
     'local': '2026-02-24 16:06+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:00Z',
     'local': '2026-02-24 16:00+01:00'},
    'runway': '24',
    'quality': ['Basic', 'Live']},
   'number': 'DFKNO',
   'callSign': 'DFKNO',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'airline': {'name': 'DFKNO'}},
  {'departure': {'airport': {'icao': 'GCTS',
     'iata': 'TFS',
     'name': 'Tenerife Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'scheduledTime': {'utc': '2026-02-24 10:55Z',
     'local': '2026-02-24 10:55+00:00'},
    'revisedTime': {'utc': '2026-02-24 10:55Z',
     'local': '2026-02-24 10:55+00:00'},
    'terminal': 'C',
    'checkInDesk': '202-213',
    'gate': 'B14',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:40Z',
     'local': '2026-02-24 16:40+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:07Z',
     'local': '2026-02-24 16:07+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:02Z',
     'local': '2026-02-24 16:02+01:00'},
    'terminal': '2',
    'baggageBelt': 'B',
    'runway': '14L',
    'quality': ['Basic', 'Live']},
   'number': 'FR 1034',
   'callSign': 'RYR5826',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-EST', 'modeS': '4CA97B', 'model': 'Boeing 737-800'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'LICC',
     'iata': 'CTA',
     'name': 'Catania',
     'countryCode': 'it',
     'timeZone': 'Europe/Rome'},
    'scheduledTime': {'utc': '2026-02-24 12:30Z',
     'local': '2026-02-24 13:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 12:22Z',
     'local': '2026-02-24 13:22+01:00'},
    'terminal': 'A',
    'checkInDesk': '37-39',
    'gate': '11',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:05Z',
     'local': '2026-02-24 16:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:09Z',
     'local': '2026-02-24 16:09+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'runway': '14L',
    'quality': ['Basic', 'Live']},
   'number': 'EW 817',
   'callSign': 'EWG7CF',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': '9H-EWG', 'modeS': '4D2087', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'GCFV',
     'iata': 'FUE',
     'name': 'Fuerteventura Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:30Z',
     'local': '2026-02-24 16:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:16Z',
     'local': '2026-02-24 16:16+01:00'},
    'terminal': '2',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'FR 7671',
   'callSign': 'RYR70LM',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-HGZ', 'modeS': '4CAD12', 'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'EGLL',
     'iata': 'LHR',
     'name': 'London',
     'countryCode': 'gb',
     'timeZone': 'Europe/London'},
    'scheduledTime': {'utc': '2026-02-24 13:45Z',
     'local': '2026-02-24 13:45+00:00'},
    'revisedTime': {'utc': '2026-02-24 14:19Z',
     'local': '2026-02-24 14:19+00:00'},
    'runwayTime': {'utc': '2026-02-24 14:20Z',
     'local': '2026-02-24 14:20+00:00'},
    'terminal': '3',
    'checkInDesk': 'E',
    'runway': '27L',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:10Z',
     'local': '2026-02-24 16:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:16Z',
     'local': '2026-02-24 16:16+01:00'},
    'terminal': '2',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'BA 998',
   'callSign': 'BAW998',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'G-EUPU', 'modeS': '4008B5', 'model': 'Airbus A319'},
   'airline': {'name': 'British', 'iata': 'BA', 'icao': 'BAW'}},
  {'departure': {'airport': {'icao': 'EDDM',
     'iata': 'MUC',
     'name': 'Munich',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 15:05Z',
     'local': '2026-02-24 16:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:05Z',
     'local': '2026-02-24 16:05+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:12Z',
     'local': '2026-02-24 16:12+01:00'},
    'terminal': '2',
    'runway': '26R',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 16:10Z',
     'local': '2026-02-24 17:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:00Z',
     'local': '2026-02-24 17:00+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'LH 1984',
   'callSign': 'DLH8FC',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AIUB', 'modeS': '3C66A2', 'model': 'Airbus A320'},
   'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'}},
  {'departure': {'airport': {'icao': 'LTFM',
     'iata': 'IST',
     'name': 'Istanbul',
     'countryCode': 'tr',
     'timeZone': 'Europe/Istanbul'},
    'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 16:15Z',
     'local': '2026-02-24 17:15+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:14Z',
     'local': '2026-02-24 17:14+01:00'},
    'terminal': '2',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'TK 1675',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A321'},
   'airline': {'name': 'Turkish', 'iata': 'TK', 'icao': 'THY'}},
  {'departure': {'airport': {'icao': 'EDDB',
     'iata': 'BER',
     'name': 'Berlin',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'terminal': '1',
    'checkInDesk': '323-326',
    'gate': 'A17',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 16:55Z',
     'local': '2026-02-24 17:55+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:55Z',
     'local': '2026-02-24 17:55+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 7',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AGWJ', 'modeS': '3C5EEA', 'model': 'Airbus A319'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'HEGN',
     'iata': 'HRG',
     'name': 'Hurghada',
     'countryCode': 'eg',
     'timeZone': 'Africa/Cairo'},
    'scheduledTime': {'utc': '2026-02-24 11:50Z',
     'local': '2026-02-24 13:50+02:00'},
    'terminal': '2',
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 17:10Z',
     'local': '2026-02-24 18:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 17:25Z',
     'local': '2026-02-24 18:25+01:00'},
    'terminal': '1',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'EW 981',
   'callSign': 'EWG981',
   'status': 'Delayed',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AEEE', 'modeS': '3C54A5', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'EDDB',
     'iata': 'BER',
     'name': 'Berlin',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 16:30Z',
     'local': '2026-02-24 17:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:30Z',
     'local': '2026-02-24 17:30+01:00'},
    'terminal': '1',
    'checkInDesk': '323-326',
    'gate': 'B01',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 17:35Z',
     'local': '2026-02-24 18:35+01:00'},
    'revisedTime': {'utc': '2026-02-24 17:35Z',
     'local': '2026-02-24 18:35+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'EW 8070',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AEWS', 'modeS': '3C56F3', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'EDDM',
     'iata': 'MUC',
     'name': 'Munich',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 16:50Z',
     'local': '2026-02-24 17:50+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:50Z',
     'local': '2026-02-24 17:50+01:00'},
    'terminal': '2',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 17:55Z',
     'local': '2026-02-24 18:55+01:00'},
    'revisedTime': {'utc': '2026-02-24 17:55Z',
     'local': '2026-02-24 18:55+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'LH 1986',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320'},
   'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'}},
  {'departure': {'airport': {'icao': 'LEMG',
     'iata': 'AGP',
     'name': 'Málaga',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},
    'scheduledTime': {'utc': '2026-02-24 14:55Z',
     'local': '2026-02-24 15:55+01:00'},
    'revisedTime': {'utc': '2026-02-24 14:52Z',
     'local': '2026-02-24 15:52+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:10Z',
     'local': '2026-02-24 16:10+01:00'},
    'terminal': 'PAX',
    'checkInDesk': '363-370',
    'gate': 'D51',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:00Z',
     'local': '2026-02-24 19:00+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:00Z',
     'local': '2026-02-24 19:00+01:00'},
    'terminal': '2',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'FR 2307',
   'callSign': 'RYR90ZG',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-ILJ', 'modeS': '4CAFF7', 'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'LEPA',
     'iata': 'PMI',
     'name': 'Palma De Mallorca',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},
    'scheduledTime': {'utc': '2026-02-24 15:45Z',
     'local': '2026-02-24 16:45+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:45Z',
     'local': '2026-02-24 16:45+01:00'},
    'terminal': 'N',
    'checkInDesk': '305-307',
    'gate': 'C40',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 19:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 19:05+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'EW 583',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A319'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LATI',
     'iata': 'TIA',
     'name': 'Tirana',
     'countryCode': 'al',
     'timeZone': 'Europe/Tirane'},
    'scheduledTime': {'utc': '2026-02-24 15:30Z',
     'local': '2026-02-24 16:30+01:00'},
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:20Z',
     'local': '2026-02-24 19:20+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:20Z',
     'local': '2026-02-24 19:20+01:00'},
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'W4 5121',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A321'},
   'airline': {'name': 'Wizz Air Malta', 'iata': 'W4', 'icao': 'WMT'}},
  {'departure': {'airport': {'icao': 'LEMG',
     'iata': 'AGP',
     'name': 'Málaga',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},
    'scheduledTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'terminal': 'PAX',
    'checkInDesk': '322-323',
    'gate': 'D42',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:40Z',
     'local': '2026-02-24 19:40+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:40Z',
     'local': '2026-02-24 19:40+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 535',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320 NEO'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LYNI',
     'iata': 'INI',
     'name': 'Niš',
     'countryCode': 'rs',
     'timeZone': 'Europe/Belgrade'},
    'scheduledTime': {'utc': '2026-02-24 16:45Z',
     'local': '2026-02-24 17:45+01:00'},
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'JU 1298',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A319'},
   'airline': {'name': 'Air Serbia', 'iata': 'JU', 'icao': 'ASL'}},
  {'departure': {'airport': {'icao': 'EGSS',
     'iata': 'STN',
     'name': 'London',
     'countryCode': 'gb',
     'timeZone': 'Europe/London'},
    'scheduledTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 18:05+00:00'},
    'revisedTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 18:05+00:00'},
    'terminal': '1',
    'gate': '42',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 19:25Z',
     'local': '2026-02-24 20:25+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:25Z',
     'local': '2026-02-24 20:25+01:00'},
    'terminal': '2',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'FR 2814',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'GCRR',
     'iata': 'ACE',
     'name': 'Lanzarote Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'scheduledTime': {'utc': '2026-02-24 15:15Z',
     'local': '2026-02-24 15:15+00:00'},
    'revisedTime': {'utc': '2026-02-24 15:15Z',
     'local': '2026-02-24 15:15+00:00'},
    'terminal': '1',
    'checkInDesk': '11-12',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 19:30Z',
     'local': '2026-02-24 20:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:30Z',
     'local': '2026-02-24 20:30+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 261',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'EDDB',
     'iata': 'BER',
     'name': 'Berlin',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'terminal': '1',
    'checkInDesk': '323-326',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 20:10Z',
     'local': '2026-02-24 21:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 20:10Z',
     'local': '2026-02-24 21:10+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 15',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AGWG', 'modeS': '3C5EE7', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LSZH',
     'iata': 'ZRH',
     'name': 'Zurich',
     'countryCode': 'ch',
     'timeZone': 'Europe/Zurich'},
    'scheduledTime': {'utc': '2026-02-24 19:10Z',
     'local': '2026-02-24 20:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:10Z',
     'local': '2026-02-24 20:10+01:00'},
    'checkInDesk': '2(5)',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 20:15Z',
     'local': '2026-02-24 21:15+01:00'},
    'revisedTime': {'utc': '2026-02-24 20:15Z',
     'local': '2026-02-24 21:15+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'EW 769',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AGWU', 'modeS': '3C5EF5', 'model': 'Airbus A319'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LEPA',
     'iata': 'PMI',
     'name': 'Palma De Mallorca',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},

In [24]:
response.json()

{'arrivals': [{'departure': {'airport': {'icao': 'LOWW',
     'iata': 'VIE',
     'name': 'Vienna',
     'countryCode': 'at',
     'timeZone': 'Europe/Vienna'},
    'scheduledTime': {'utc': '2026-02-24 13:00Z',
     'local': '2026-02-24 14:00+01:00'},
    'revisedTime': {'utc': '2026-02-24 13:02Z',
     'local': '2026-02-24 14:02+01:00'},
    'runwayTime': {'utc': '2026-02-24 13:03Z',
     'local': '2026-02-24 14:03+01:00'},
    'terminal': '1',
    'checkInDesk': '151-162',
    'gate': 'C36',
    'runway': '34',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 14:30Z',
     'local': '2026-02-24 15:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 14:25Z',
     'local': '2026-02-24 15:25+01:00'},
    'terminal': '2',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'FR 9480',
   'callSign': 'RYR51NQ',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-HAW', 'modeS': '4CA95E', 'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'GCLP',
     'iata': 'LPA',
     'name': 'Gran Canaria Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'scheduledTime': {'utc': '2026-02-24 10:40Z',
     'local': '2026-02-24 10:40+00:00'},
    'revisedTime': {'utc': '2026-02-24 10:40Z',
     'local': '2026-02-24 10:40+00:00'},
    'terminal': '1',
    'checkInDesk': '315-317',
    'gate': 'C22',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:10Z',
     'local': '2026-02-24 16:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 14:58Z',
     'local': '2026-02-24 15:58+01:00'},
    'terminal': '2',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'XR 524',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 737-800'},
   'airline': {'name': 'Corendon  Europe', 'iata': 'XR', 'icao': 'CXI'}},
  {'departure': {'airport': {'name': 'Unknown'}, 'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:00Z',
     'local': '2026-02-24 16:00+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:06Z',
     'local': '2026-02-24 16:06+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:00Z',
     'local': '2026-02-24 16:00+01:00'},
    'runway': '24',
    'quality': ['Basic', 'Live']},
   'number': 'DFKNO',
   'callSign': 'DFKNO',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'airline': {'name': 'DFKNO'}},
  {'departure': {'airport': {'icao': 'GCTS',
     'iata': 'TFS',
     'name': 'Tenerife Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'scheduledTime': {'utc': '2026-02-24 10:55Z',
     'local': '2026-02-24 10:55+00:00'},
    'revisedTime': {'utc': '2026-02-24 10:55Z',
     'local': '2026-02-24 10:55+00:00'},
    'terminal': 'C',
    'checkInDesk': '202-213',
    'gate': 'B14',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:40Z',
     'local': '2026-02-24 16:40+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:07Z',
     'local': '2026-02-24 16:07+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:02Z',
     'local': '2026-02-24 16:02+01:00'},
    'terminal': '2',
    'baggageBelt': 'B',
    'runway': '14L',
    'quality': ['Basic', 'Live']},
   'number': 'FR 1034',
   'callSign': 'RYR5826',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-EST', 'modeS': '4CA97B', 'model': 'Boeing 737-800'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'LICC',
     'iata': 'CTA',
     'name': 'Catania',
     'countryCode': 'it',
     'timeZone': 'Europe/Rome'},
    'scheduledTime': {'utc': '2026-02-24 12:30Z',
     'local': '2026-02-24 13:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 12:22Z',
     'local': '2026-02-24 13:22+01:00'},
    'terminal': 'A',
    'checkInDesk': '37-39',
    'gate': '11',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:05Z',
     'local': '2026-02-24 16:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:09Z',
     'local': '2026-02-24 16:09+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'runway': '14L',
    'quality': ['Basic', 'Live']},
   'number': 'EW 817',
   'callSign': 'EWG7CF',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': '9H-EWG', 'modeS': '4D2087', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'GCFV',
     'iata': 'FUE',
     'name': 'Fuerteventura Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:30Z',
     'local': '2026-02-24 16:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:16Z',
     'local': '2026-02-24 16:16+01:00'},
    'terminal': '2',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'FR 7671',
   'callSign': 'RYR70LM',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-HGZ', 'modeS': '4CAD12', 'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'EGLL',
     'iata': 'LHR',
     'name': 'London',
     'countryCode': 'gb',
     'timeZone': 'Europe/London'},
    'scheduledTime': {'utc': '2026-02-24 13:45Z',
     'local': '2026-02-24 13:45+00:00'},
    'revisedTime': {'utc': '2026-02-24 14:19Z',
     'local': '2026-02-24 14:19+00:00'},
    'runwayTime': {'utc': '2026-02-24 14:20Z',
     'local': '2026-02-24 14:20+00:00'},
    'terminal': '3',
    'checkInDesk': 'E',
    'runway': '27L',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:10Z',
     'local': '2026-02-24 16:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:16Z',
     'local': '2026-02-24 16:16+01:00'},
    'terminal': '2',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'BA 998',
   'callSign': 'BAW998',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'G-EUPU', 'modeS': '4008B5', 'model': 'Airbus A319'},
   'airline': {'name': 'British', 'iata': 'BA', 'icao': 'BAW'}},
  {'departure': {'airport': {'icao': 'EDDM',
     'iata': 'MUC',
     'name': 'Munich',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 15:05Z',
     'local': '2026-02-24 16:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:05Z',
     'local': '2026-02-24 16:05+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:12Z',
     'local': '2026-02-24 16:12+01:00'},
    'terminal': '2',
    'runway': '26R',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 16:10Z',
     'local': '2026-02-24 17:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:00Z',
     'local': '2026-02-24 17:00+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'LH 1984',
   'callSign': 'DLH8FC',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AIUB', 'modeS': '3C66A2', 'model': 'Airbus A320'},
   'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'}},
  {'departure': {'airport': {'icao': 'LTFM',
     'iata': 'IST',
     'name': 'Istanbul',
     'countryCode': 'tr',
     'timeZone': 'Europe/Istanbul'},
    'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 16:15Z',
     'local': '2026-02-24 17:15+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:14Z',
     'local': '2026-02-24 17:14+01:00'},
    'terminal': '2',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'TK 1675',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A321'},
   'airline': {'name': 'Turkish', 'iata': 'TK', 'icao': 'THY'}},
  {'departure': {'airport': {'icao': 'EDDB',
     'iata': 'BER',
     'name': 'Berlin',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'terminal': '1',
    'checkInDesk': '323-326',
    'gate': 'A17',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 16:55Z',
     'local': '2026-02-24 17:55+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:55Z',
     'local': '2026-02-24 17:55+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 7',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AGWJ', 'modeS': '3C5EEA', 'model': 'Airbus A319'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'HEGN',
     'iata': 'HRG',
     'name': 'Hurghada',
     'countryCode': 'eg',
     'timeZone': 'Africa/Cairo'},
    'scheduledTime': {'utc': '2026-02-24 11:50Z',
     'local': '2026-02-24 13:50+02:00'},
    'terminal': '2',
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 17:10Z',
     'local': '2026-02-24 18:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 17:25Z',
     'local': '2026-02-24 18:25+01:00'},
    'terminal': '1',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'EW 981',
   'callSign': 'EWG981',
   'status': 'Delayed',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AEEE', 'modeS': '3C54A5', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'EDDB',
     'iata': 'BER',
     'name': 'Berlin',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 16:30Z',
     'local': '2026-02-24 17:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:30Z',
     'local': '2026-02-24 17:30+01:00'},
    'terminal': '1',
    'checkInDesk': '323-326',
    'gate': 'B01',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 17:35Z',
     'local': '2026-02-24 18:35+01:00'},
    'revisedTime': {'utc': '2026-02-24 17:35Z',
     'local': '2026-02-24 18:35+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'EW 8070',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AEWS', 'modeS': '3C56F3', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'EDDM',
     'iata': 'MUC',
     'name': 'Munich',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 16:50Z',
     'local': '2026-02-24 17:50+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:50Z',
     'local': '2026-02-24 17:50+01:00'},
    'terminal': '2',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 17:55Z',
     'local': '2026-02-24 18:55+01:00'},
    'revisedTime': {'utc': '2026-02-24 17:55Z',
     'local': '2026-02-24 18:55+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'LH 1986',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320'},
   'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'}},
  {'departure': {'airport': {'icao': 'LEMG',
     'iata': 'AGP',
     'name': 'Málaga',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},
    'scheduledTime': {'utc': '2026-02-24 14:55Z',
     'local': '2026-02-24 15:55+01:00'},
    'revisedTime': {'utc': '2026-02-24 14:52Z',
     'local': '2026-02-24 15:52+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:10Z',
     'local': '2026-02-24 16:10+01:00'},
    'terminal': 'PAX',
    'checkInDesk': '363-370',
    'gate': 'D51',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:00Z',
     'local': '2026-02-24 19:00+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:00Z',
     'local': '2026-02-24 19:00+01:00'},
    'terminal': '2',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'FR 2307',
   'callSign': 'RYR90ZG',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-ILJ', 'modeS': '4CAFF7', 'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'LEPA',
     'iata': 'PMI',
     'name': 'Palma De Mallorca',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},
    'scheduledTime': {'utc': '2026-02-24 15:45Z',
     'local': '2026-02-24 16:45+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:45Z',
     'local': '2026-02-24 16:45+01:00'},
    'terminal': 'N',
    'checkInDesk': '305-307',
    'gate': 'C40',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 19:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 19:05+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'EW 583',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A319'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LATI',
     'iata': 'TIA',
     'name': 'Tirana',
     'countryCode': 'al',
     'timeZone': 'Europe/Tirane'},
    'scheduledTime': {'utc': '2026-02-24 15:30Z',
     'local': '2026-02-24 16:30+01:00'},
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:20Z',
     'local': '2026-02-24 19:20+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:20Z',
     'local': '2026-02-24 19:20+01:00'},
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'W4 5121',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A321'},
   'airline': {'name': 'Wizz Air Malta', 'iata': 'W4', 'icao': 'WMT'}},
  {'departure': {'airport': {'icao': 'LEMG',
     'iata': 'AGP',
     'name': 'Málaga',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},
    'scheduledTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'terminal': 'PAX',
    'checkInDesk': '322-323',
    'gate': 'D42',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:40Z',
     'local': '2026-02-24 19:40+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:40Z',
     'local': '2026-02-24 19:40+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 535',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320 NEO'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LYNI',
     'iata': 'INI',
     'name': 'Niš',
     'countryCode': 'rs',
     'timeZone': 'Europe/Belgrade'},
    'scheduledTime': {'utc': '2026-02-24 16:45Z',
     'local': '2026-02-24 17:45+01:00'},
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'JU 1298',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A319'},
   'airline': {'name': 'Air Serbia', 'iata': 'JU', 'icao': 'ASL'}},
  {'departure': {'airport': {'icao': 'EGSS',
     'iata': 'STN',
     'name': 'London',
     'countryCode': 'gb',
     'timeZone': 'Europe/London'},
    'scheduledTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 18:05+00:00'},
    'revisedTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 18:05+00:00'},
    'terminal': '1',
    'gate': '42',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 19:25Z',
     'local': '2026-02-24 20:25+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:25Z',
     'local': '2026-02-24 20:25+01:00'},
    'terminal': '2',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'FR 2814',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'GCRR',
     'iata': 'ACE',
     'name': 'Lanzarote Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'scheduledTime': {'utc': '2026-02-24 15:15Z',
     'local': '2026-02-24 15:15+00:00'},
    'revisedTime': {'utc': '2026-02-24 15:15Z',
     'local': '2026-02-24 15:15+00:00'},
    'terminal': '1',
    'checkInDesk': '11-12',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 19:30Z',
     'local': '2026-02-24 20:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:30Z',
     'local': '2026-02-24 20:30+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 261',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'EDDB',
     'iata': 'BER',
     'name': 'Berlin',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'terminal': '1',
    'checkInDesk': '323-326',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 20:10Z',
     'local': '2026-02-24 21:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 20:10Z',
     'local': '2026-02-24 21:10+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 15',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AGWG', 'modeS': '3C5EE7', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LSZH',
     'iata': 'ZRH',
     'name': 'Zurich',
     'countryCode': 'ch',
     'timeZone': 'Europe/Zurich'},
    'scheduledTime': {'utc': '2026-02-24 19:10Z',
     'local': '2026-02-24 20:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:10Z',
     'local': '2026-02-24 20:10+01:00'},
    'checkInDesk': '2(5)',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 20:15Z',
     'local': '2026-02-24 21:15+01:00'},
    'revisedTime': {'utc': '2026-02-24 20:15Z',
     'local': '2026-02-24 21:15+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'EW 769',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AGWU', 'modeS': '3C5EF5', 'model': 'Airbus A319'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LEPA',
     'iata': 'PMI',
     'name': 'Palma De Mallorca',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},

In [26]:
import requests
import os

# 1️Get airport metadata
lat, lon = 50.9413, 6.9583  # Cologne airport approx
url_airport = f"https://aerodatabox.p.rapidapi.com/airports/search/location/{lat}/{lon}/km/50/10"

headers = {
    "X-RapidAPI-Key": os.getenv("FlightsAPI"),
    "X-RapidAPI-Host": "aerodatabox.p.rapidapi.com"
}

querystring = {"withFlightInfoOnly": "true"}

airport_response = requests.get(url_airport, headers=headers, params=querystring)
airport_data = airport_response.json()
print(airport_data)  # Inspect metadata

{'searchBy': {'lat': 50.9413, 'lon': 6.9583}, 'count': 2, 'items': [{'icao': 'EDDK', 'iata': 'CGN', 'name': 'Cologne Bonn', 'shortName': 'Bonn', 'municipalityName': 'Cologne', 'location': {'lat': 50.8659, 'lon': 7.142739}, 'countryCode': 'DE', 'timeZone': 'Europe/Berlin'}, {'icao': 'EDDL', 'iata': 'DUS', 'name': 'Düsseldorf', 'shortName': 'Düsseldorf', 'municipalityName': 'Düsseldorf', 'location': {'lat': 51.2895, 'lon': 6.766779}, 'countryCode': 'DE', 'timeZone': 'Europe/Berlin'}]}

In [27]:
response.json()

{'arrivals': [{'departure': {'airport': {'icao': 'LOWW',
     'iata': 'VIE',
     'name': 'Vienna',
     'countryCode': 'at',
     'timeZone': 'Europe/Vienna'},
    'scheduledTime': {'utc': '2026-02-24 13:00Z',
     'local': '2026-02-24 14:00+01:00'},
    'revisedTime': {'utc': '2026-02-24 13:02Z',
     'local': '2026-02-24 14:02+01:00'},
    'runwayTime': {'utc': '2026-02-24 13:03Z',
     'local': '2026-02-24 14:03+01:00'},
    'terminal': '1',
    'checkInDesk': '151-162',
    'gate': 'C36',
    'runway': '34',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 14:30Z',
     'local': '2026-02-24 15:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 14:25Z',
     'local': '2026-02-24 15:25+01:00'},
    'terminal': '2',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'FR 9480',
   'callSign': 'RYR51NQ',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-HAW', 'modeS': '4CA95E', 'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'GCLP',
     'iata': 'LPA',
     'name': 'Gran Canaria Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'scheduledTime': {'utc': '2026-02-24 10:40Z',
     'local': '2026-02-24 10:40+00:00'},
    'revisedTime': {'utc': '2026-02-24 10:40Z',
     'local': '2026-02-24 10:40+00:00'},
    'terminal': '1',
    'checkInDesk': '315-317',
    'gate': 'C22',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:10Z',
     'local': '2026-02-24 16:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 14:58Z',
     'local': '2026-02-24 15:58+01:00'},
    'terminal': '2',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'XR 524',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 737-800'},
   'airline': {'name': 'Corendon  Europe', 'iata': 'XR', 'icao': 'CXI'}},
  {'departure': {'airport': {'name': 'Unknown'}, 'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:00Z',
     'local': '2026-02-24 16:00+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:06Z',
     'local': '2026-02-24 16:06+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:00Z',
     'local': '2026-02-24 16:00+01:00'},
    'runway': '24',
    'quality': ['Basic', 'Live']},
   'number': 'DFKNO',
   'callSign': 'DFKNO',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'airline': {'name': 'DFKNO'}},
  {'departure': {'airport': {'icao': 'GCTS',
     'iata': 'TFS',
     'name': 'Tenerife Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'scheduledTime': {'utc': '2026-02-24 10:55Z',
     'local': '2026-02-24 10:55+00:00'},
    'revisedTime': {'utc': '2026-02-24 10:55Z',
     'local': '2026-02-24 10:55+00:00'},
    'terminal': 'C',
    'checkInDesk': '202-213',
    'gate': 'B14',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:40Z',
     'local': '2026-02-24 16:40+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:07Z',
     'local': '2026-02-24 16:07+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:02Z',
     'local': '2026-02-24 16:02+01:00'},
    'terminal': '2',
    'baggageBelt': 'B',
    'runway': '14L',
    'quality': ['Basic', 'Live']},
   'number': 'FR 1034',
   'callSign': 'RYR5826',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-EST', 'modeS': '4CA97B', 'model': 'Boeing 737-800'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'LICC',
     'iata': 'CTA',
     'name': 'Catania',
     'countryCode': 'it',
     'timeZone': 'Europe/Rome'},
    'scheduledTime': {'utc': '2026-02-24 12:30Z',
     'local': '2026-02-24 13:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 12:22Z',
     'local': '2026-02-24 13:22+01:00'},
    'terminal': 'A',
    'checkInDesk': '37-39',
    'gate': '11',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:05Z',
     'local': '2026-02-24 16:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:09Z',
     'local': '2026-02-24 16:09+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'runway': '14L',
    'quality': ['Basic', 'Live']},
   'number': 'EW 817',
   'callSign': 'EWG7CF',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': '9H-EWG', 'modeS': '4D2087', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'GCFV',
     'iata': 'FUE',
     'name': 'Fuerteventura Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:30Z',
     'local': '2026-02-24 16:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:16Z',
     'local': '2026-02-24 16:16+01:00'},
    'terminal': '2',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'FR 7671',
   'callSign': 'RYR70LM',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-HGZ', 'modeS': '4CAD12', 'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'EGLL',
     'iata': 'LHR',
     'name': 'London',
     'countryCode': 'gb',
     'timeZone': 'Europe/London'},
    'scheduledTime': {'utc': '2026-02-24 13:45Z',
     'local': '2026-02-24 13:45+00:00'},
    'revisedTime': {'utc': '2026-02-24 14:19Z',
     'local': '2026-02-24 14:19+00:00'},
    'runwayTime': {'utc': '2026-02-24 14:20Z',
     'local': '2026-02-24 14:20+00:00'},
    'terminal': '3',
    'checkInDesk': 'E',
    'runway': '27L',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 15:10Z',
     'local': '2026-02-24 16:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:16Z',
     'local': '2026-02-24 16:16+01:00'},
    'terminal': '2',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'BA 998',
   'callSign': 'BAW998',
   'status': 'Arrived',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'G-EUPU', 'modeS': '4008B5', 'model': 'Airbus A319'},
   'airline': {'name': 'British', 'iata': 'BA', 'icao': 'BAW'}},
  {'departure': {'airport': {'icao': 'EDDM',
     'iata': 'MUC',
     'name': 'Munich',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 15:05Z',
     'local': '2026-02-24 16:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:05Z',
     'local': '2026-02-24 16:05+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:12Z',
     'local': '2026-02-24 16:12+01:00'},
    'terminal': '2',
    'runway': '26R',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 16:10Z',
     'local': '2026-02-24 17:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:00Z',
     'local': '2026-02-24 17:00+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'LH 1984',
   'callSign': 'DLH8FC',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AIUB', 'modeS': '3C66A2', 'model': 'Airbus A320'},
   'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'}},
  {'departure': {'airport': {'icao': 'LTFM',
     'iata': 'IST',
     'name': 'Istanbul',
     'countryCode': 'tr',
     'timeZone': 'Europe/Istanbul'},
    'quality': []},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 16:15Z',
     'local': '2026-02-24 17:15+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:14Z',
     'local': '2026-02-24 17:14+01:00'},
    'terminal': '2',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'TK 1675',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A321'},
   'airline': {'name': 'Turkish', 'iata': 'TK', 'icao': 'THY'}},
  {'departure': {'airport': {'icao': 'EDDB',
     'iata': 'BER',
     'name': 'Berlin',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'terminal': '1',
    'checkInDesk': '323-326',
    'gate': 'A17',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 16:55Z',
     'local': '2026-02-24 17:55+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:55Z',
     'local': '2026-02-24 17:55+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 7',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AGWJ', 'modeS': '3C5EEA', 'model': 'Airbus A319'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'HEGN',
     'iata': 'HRG',
     'name': 'Hurghada',
     'countryCode': 'eg',
     'timeZone': 'Africa/Cairo'},
    'scheduledTime': {'utc': '2026-02-24 11:50Z',
     'local': '2026-02-24 13:50+02:00'},
    'terminal': '2',
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 17:10Z',
     'local': '2026-02-24 18:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 17:25Z',
     'local': '2026-02-24 18:25+01:00'},
    'terminal': '1',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'EW 981',
   'callSign': 'EWG981',
   'status': 'Delayed',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AEEE', 'modeS': '3C54A5', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'EDDB',
     'iata': 'BER',
     'name': 'Berlin',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 16:30Z',
     'local': '2026-02-24 17:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:30Z',
     'local': '2026-02-24 17:30+01:00'},
    'terminal': '1',
    'checkInDesk': '323-326',
    'gate': 'B01',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 17:35Z',
     'local': '2026-02-24 18:35+01:00'},
    'revisedTime': {'utc': '2026-02-24 17:35Z',
     'local': '2026-02-24 18:35+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'EW 8070',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AEWS', 'modeS': '3C56F3', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'EDDM',
     'iata': 'MUC',
     'name': 'Munich',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 16:50Z',
     'local': '2026-02-24 17:50+01:00'},
    'revisedTime': {'utc': '2026-02-24 16:50Z',
     'local': '2026-02-24 17:50+01:00'},
    'terminal': '2',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 17:55Z',
     'local': '2026-02-24 18:55+01:00'},
    'revisedTime': {'utc': '2026-02-24 17:55Z',
     'local': '2026-02-24 18:55+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'LH 1986',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320'},
   'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'}},
  {'departure': {'airport': {'icao': 'LEMG',
     'iata': 'AGP',
     'name': 'Málaga',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},
    'scheduledTime': {'utc': '2026-02-24 14:55Z',
     'local': '2026-02-24 15:55+01:00'},
    'revisedTime': {'utc': '2026-02-24 14:52Z',
     'local': '2026-02-24 15:52+01:00'},
    'runwayTime': {'utc': '2026-02-24 15:10Z',
     'local': '2026-02-24 16:10+01:00'},
    'terminal': 'PAX',
    'checkInDesk': '363-370',
    'gate': 'D51',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:00Z',
     'local': '2026-02-24 19:00+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:00Z',
     'local': '2026-02-24 19:00+01:00'},
    'terminal': '2',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'FR 2307',
   'callSign': 'RYR90ZG',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'EI-ILJ', 'modeS': '4CAFF7', 'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'LEPA',
     'iata': 'PMI',
     'name': 'Palma De Mallorca',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},
    'scheduledTime': {'utc': '2026-02-24 15:45Z',
     'local': '2026-02-24 16:45+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:45Z',
     'local': '2026-02-24 16:45+01:00'},
    'terminal': 'N',
    'checkInDesk': '305-307',
    'gate': 'C40',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 19:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 19:05+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'EW 583',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A319'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LATI',
     'iata': 'TIA',
     'name': 'Tirana',
     'countryCode': 'al',
     'timeZone': 'Europe/Tirane'},
    'scheduledTime': {'utc': '2026-02-24 15:30Z',
     'local': '2026-02-24 16:30+01:00'},
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:20Z',
     'local': '2026-02-24 19:20+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:20Z',
     'local': '2026-02-24 19:20+01:00'},
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'W4 5121',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A321'},
   'airline': {'name': 'Wizz Air Malta', 'iata': 'W4', 'icao': 'WMT'}},
  {'departure': {'airport': {'icao': 'LEMG',
     'iata': 'AGP',
     'name': 'Málaga',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},
    'scheduledTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'revisedTime': {'utc': '2026-02-24 15:50Z',
     'local': '2026-02-24 16:50+01:00'},
    'terminal': 'PAX',
    'checkInDesk': '322-323',
    'gate': 'D42',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 18:40Z',
     'local': '2026-02-24 19:40+01:00'},
    'revisedTime': {'utc': '2026-02-24 18:40Z',
     'local': '2026-02-24 19:40+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 535',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320 NEO'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LYNI',
     'iata': 'INI',
     'name': 'Niš',
     'countryCode': 'rs',
     'timeZone': 'Europe/Belgrade'},
    'scheduledTime': {'utc': '2026-02-24 16:45Z',
     'local': '2026-02-24 17:45+01:00'},
    'quality': ['Basic']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'JU 1298',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A319'},
   'airline': {'name': 'Air Serbia', 'iata': 'JU', 'icao': 'ASL'}},
  {'departure': {'airport': {'icao': 'EGSS',
     'iata': 'STN',
     'name': 'London',
     'countryCode': 'gb',
     'timeZone': 'Europe/London'},
    'scheduledTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 18:05+00:00'},
    'revisedTime': {'utc': '2026-02-24 18:05Z',
     'local': '2026-02-24 18:05+00:00'},
    'terminal': '1',
    'gate': '42',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 19:25Z',
     'local': '2026-02-24 20:25+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:25Z',
     'local': '2026-02-24 20:25+01:00'},
    'terminal': '2',
    'baggageBelt': 'D',
    'quality': ['Basic', 'Live']},
   'number': 'FR 2814',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Boeing 737'},
   'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}},
  {'departure': {'airport': {'icao': 'GCRR',
     'iata': 'ACE',
     'name': 'Lanzarote Island',
     'countryCode': 'es',
     'timeZone': 'Atlantic/Canary'},
    'scheduledTime': {'utc': '2026-02-24 15:15Z',
     'local': '2026-02-24 15:15+00:00'},
    'revisedTime': {'utc': '2026-02-24 15:15Z',
     'local': '2026-02-24 15:15+00:00'},
    'terminal': '1',
    'checkInDesk': '11-12',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 19:30Z',
     'local': '2026-02-24 20:30+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:30Z',
     'local': '2026-02-24 20:30+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 261',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'EDDB',
     'iata': 'BER',
     'name': 'Berlin',
     'countryCode': 'de',
     'timeZone': 'Europe/Berlin'},
    'scheduledTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:05Z',
     'local': '2026-02-24 20:05+01:00'},
    'terminal': '1',
    'checkInDesk': '323-326',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 20:10Z',
     'local': '2026-02-24 21:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 20:10Z',
     'local': '2026-02-24 21:10+01:00'},
    'terminal': '1',
    'baggageBelt': 'C',
    'quality': ['Basic', 'Live']},
   'number': 'EW 15',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AGWG', 'modeS': '3C5EE7', 'model': 'Airbus A320'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LSZH',
     'iata': 'ZRH',
     'name': 'Zurich',
     'countryCode': 'ch',
     'timeZone': 'Europe/Zurich'},
    'scheduledTime': {'utc': '2026-02-24 19:10Z',
     'local': '2026-02-24 20:10+01:00'},
    'revisedTime': {'utc': '2026-02-24 19:10Z',
     'local': '2026-02-24 20:10+01:00'},
    'checkInDesk': '2(5)',
    'quality': ['Basic', 'Live']},
   'arrival': {'scheduledTime': {'utc': '2026-02-24 20:15Z',
     'local': '2026-02-24 21:15+01:00'},
    'revisedTime': {'utc': '2026-02-24 20:15Z',
     'local': '2026-02-24 21:15+01:00'},
    'terminal': '1',
    'baggageBelt': 'B',
    'quality': ['Basic', 'Live']},
   'number': 'EW 769',
   'status': 'Expected',
   'codeshareStatus': 'IsOperator',
   'isCargo': False,
   'aircraft': {'reg': 'D-AGWU', 'modeS': '3C5EF5', 'model': 'Airbus A319'},
   'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}},
  {'departure': {'airport': {'icao': 'LEPA',
     'iata': 'PMI',
     'name': 'Palma De Mallorca',
     'countryCode': 'es',
     'timeZone': 'Europe/Madrid'},

In [28]:
# Use the IATA code from airport_data
iata_code = airport_data["items"][0]["iata"]

url_arrivals = f"https://aerodatabox.p.rapidapi.com/flights/airports/iata/{iata_code}"
querystring_arrivals = {
    "offsetMinutes": -120,
    "durationMinutes": 720,
    "withLeg": True,
    "direction": "Arrival",
    "withLocation": True
}

arrivals_response = requests.get(url_arrivals, headers=headers, params=querystring_arrivals)
arrivals_data = arrivals_response.json()
print(arrivals_data)

{'arrivals': [{'departure': {'airport': {'icao': 'LOWW', 'iata': 'VIE', 'name': 'Vienna', 'countryCode': 'at', 'timeZone': 'Europe/Vienna'}, 'scheduledTime': {'utc': '2026-02-24 13:00Z', 'local': '2026-02-24 14:00+01:00'}, 'revisedTime': {'utc': '2026-02-24 13:02Z', 'local': '2026-02-24 14:02+01:00'}, 'runwayTime': {'utc': '2026-02-24 13:03Z', 'local': '2026-02-24 14:03+01:00'}, 'terminal': '1', 'checkInDesk': '151-162', 'gate': 'C36', 'runway': '34', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 14:30Z', 'local': '2026-02-24 15:30+01:00'}, 'revisedTime': {'utc': '2026-02-24 14:25Z', 'local': '2026-02-24 15:25+01:00'}, 'terminal': '2', 'baggageBelt': 'B', 'quality': ['Basic', 'Live']}, 'number': 'FR 9480', 'callSign': 'RYR51NQ', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'EI-HAW', 'modeS': '4CA95E', 'model': 'Boeing 737'}, 'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}}, {'departure': {'airport': {'icao': 'GCLP', 'iata': 'LPA', 'name': 'Gran Canaria Island', 'countryCode': 'es', 'timeZone': 'Atlantic/Canary'}, 'scheduledTime': {'utc': '2026-02-24 10:40Z', 'local': '2026-02-24 10:40+00:00'}, 'revisedTime': {'utc': '2026-02-24 10:40Z', 'local': '2026-02-24 10:40+00:00'}, 'terminal': '1', 'checkInDesk': '315-317', 'gate': 'C22', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 15:10Z', 'local': '2026-02-24 16:10+01:00'}, 'revisedTime': {'utc': '2026-02-24 14:58Z', 'local': '2026-02-24 15:58+01:00'}, 'terminal': '2', 'baggageBelt': 'C', 'quality': ['Basic', 'Live']}, 'number': 'XR 524', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Boeing 737-800'}, 'airline': {'name': 'Corendon  Europe', 'iata': 'XR', 'icao': 'CXI'}}, {'departure': {'airport': {'name': 'Unknown'}, 'quality': []}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 15:00Z', 'local': '2026-02-24 16:00+01:00'}, 'revisedTime': {'utc': '2026-02-24 15:06Z', 'local': '2026-02-24 16:06+01:00'}, 'runwayTime': {'utc': '2026-02-24 15:00Z', 'local': '2026-02-24 16:00+01:00'}, 'runway': '24', 'quality': ['Basic', 'Live']}, 'number': 'DFKNO', 'callSign': 'DFKNO', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'airline': {'name': 'DFKNO'}}, {'departure': {'airport': {'icao': 'GCTS', 'iata': 'TFS', 'name': 'Tenerife Island', 'countryCode': 'es', 'timeZone': 'Atlantic/Canary'}, 'scheduledTime': {'utc': '2026-02-24 10:55Z', 'local': '2026-02-24 10:55+00:00'}, 'revisedTime': {'utc': '2026-02-24 10:55Z', 'local': '2026-02-24 10:55+00:00'}, 'terminal': 'C', 'checkInDesk': '202-213', 'gate': 'B14', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 15:40Z', 'local': '2026-02-24 16:40+01:00'}, 'revisedTime': {'utc': '2026-02-24 15:07Z', 'local': '2026-02-24 16:07+01:00'}, 'runwayTime': {'utc': '2026-02-24 15:02Z', 'local': '2026-02-24 16:02+01:00'}, 'terminal': '2', 'baggageBelt': 'B', 'runway': '14L', 'quality': ['Basic', 'Live']}, 'number': 'FR 1034', 'callSign': 'RYR5826', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'EI-EST', 'modeS': '4CA97B', 'model': 'Boeing 737-800'}, 'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}}, {'departure': {'airport': {'icao': 'LICC', 'iata': 'CTA', 'name': 'Catania', 'countryCode': 'it', 'timeZone': 'Europe/Rome'}, 'scheduledTime': {'utc': '2026-02-24 12:30Z', 'local': '2026-02-24 13:30+01:00'}, 'revisedTime': {'utc': '2026-02-24 12:22Z', 'local': '2026-02-24 13:22+01:00'}, 'terminal': 'A', 'checkInDesk': '37-39', 'gate': '11', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 15:05Z', 'local': '2026-02-24 16:05+01:00'}, 'revisedTime': {'utc': '2026-02-24 15:09Z', 'local': '2026-02-24 16:09+01:00'}, 'terminal': '1', 'baggageBelt': 'B', 'runway': '14L', 'quality': ['Basic', 'Live']}, 'number': 'EW 817', 'callSign': 'EWG7CF', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': '9H-EWG', 'modeS': '4D2087', 'model': 'Airbus A320'}, 'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}}, {'departure': {'airport': {'icao': 'GCFV', 'iata': 'FUE', 'name': 'Fuerteventura Island', 'countryCode': 'es', 'timeZone': 'Atlantic/Canary'}, 'quality': []}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 15:30Z', 'local': '2026-02-24 16:30+01:00'}, 'revisedTime': {'utc': '2026-02-24 15:16Z', 'local': '2026-02-24 16:16+01:00'}, 'terminal': '2', 'baggageBelt': 'C', 'quality': ['Basic', 'Live']}, 'number': 'FR 7671', 'callSign': 'RYR70LM', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'EI-HGZ', 'modeS': '4CAD12', 'model': 'Boeing 737'}, 'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}}, {'departure': {'airport': {'icao': 'EGLL', 'iata': 'LHR', 'name': 'London', 'countryCode': 'gb', 'timeZone': 'Europe/London'}, 'scheduledTime': {'utc': '2026-02-24 13:45Z', 'local': '2026-02-24 13:45+00:00'}, 'revisedTime': {'utc': '2026-02-24 14:19Z', 'local': '2026-02-24 14:19+00:00'}, 'runwayTime': {'utc': '2026-02-24 14:20Z', 'local': '2026-02-24 14:20+00:00'}, 'terminal': '3', 'checkInDesk': 'E', 'runway': '27L', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 15:10Z', 'local': '2026-02-24 16:10+01:00'}, 'revisedTime': {'utc': '2026-02-24 15:16Z', 'local': '2026-02-24 16:16+01:00'}, 'terminal': '2', 'baggageBelt': 'D', 'quality': ['Basic', 'Live']}, 'number': 'BA 998', 'callSign': 'BAW998', 'status': 'Arrived', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'G-EUPU', 'modeS': '4008B5', 'model': 'Airbus A319'}, 'airline': {'name': 'British', 'iata': 'BA', 'icao': 'BAW'}}, {'departure': {'airport': {'icao': 'EDDM', 'iata': 'MUC', 'name': 'Munich', 'countryCode': 'de', 'timeZone': 'Europe/Berlin'}, 'scheduledTime': {'utc': '2026-02-24 15:05Z', 'local': '2026-02-24 16:05+01:00'}, 'revisedTime': {'utc': '2026-02-24 15:05Z', 'local': '2026-02-24 16:05+01:00'}, 'runwayTime': {'utc': '2026-02-24 15:12Z', 'local': '2026-02-24 16:12+01:00'}, 'terminal': '2', 'runway': '26R', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 16:10Z', 'local': '2026-02-24 17:10+01:00'}, 'revisedTime': {'utc': '2026-02-24 16:00Z', 'local': '2026-02-24 17:00+01:00'}, 'terminal': '1', 'baggageBelt': 'C', 'quality': ['Basic', 'Live']}, 'number': 'LH 1984', 'callSign': 'DLH8FC', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'D-AIUB', 'modeS': '3C66A2', 'model': 'Airbus A320'}, 'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'}, 'location': {'pressureAltitude': {'meter': 2324.1, 'km': 2.32, 'mile': 1.44, 'nm': 1.25, 'feet': 7625.0}, 'altitude': {'meter': 2324.1, 'km': 2.32, 'mile': 1.44, 'nm': 1.25, 'feet': 7625.0}, 'pressure': {'hPa': 0.0, 'inHg': 0.0, 'mmHg': 0.0}, 'groundSpeed': {'kt': 233.0, 'kmPerHour': 431.0, 'miPerHour': 268.0, 'meterPerSecond': 120.0}, 'trueTrack': {'deg': 296.6, 'rad': 5.176646667941625}, 'vsiFpm': -1856, 'reportedAtUtc': '2026-02-24 15:52Z', 'lat': 50.985077, 'lon': 7.256915}}, {'departure': {'airport': {'icao': 'LTFM', 'iata': 'IST', 'name': 'Istanbul', 'countryCode': 'tr', 'timeZone': 'Europe/Istanbul'}, 'quality': []}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 16:15Z', 'local': '2026-02-24 17:15+01:00'}, 'revisedTime': {'utc': '2026-02-24 16:14Z', 'local': '2026-02-24 17:14+01:00'}, 'terminal': '2', 'baggageBelt': 'D', 'quality': ['Basic', 'Live']}, 'number': 'TK 1675', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A321'}, 'airline': {'name': 'Turkish', 'iata': 'TK', 'icao': 'THY'}}, {'departure': {'airport': {'icao': 'EDDB', 'iata': 'BER', 'name': 'Berlin', 'countryCode': 'de', 'timeZone': 'Europe/Berlin'}, 'scheduledTime': {'utc': '2026-02-24 15:50Z', 'local': '2026-02-24 16:50+01:00'}, 'revisedTime': {'utc': '2026-02-24 15:50Z', 'local': '2026-02-24 16:50+01:00'}, 'terminal': '1', 'checkInDesk': '323-326', 'gate': 'A17', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 16:55Z', 'local': '2026-02-24 17:55+01:00'}, 'revisedTime': {'utc': '2026-02-24 16:55Z', 'local': '2026-02-24 17:55+01:00'}, 'terminal': '1', 'baggageBelt': 'C', 'quality': ['Basic', 'Live']}, 'number': 'EW 7', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'D-AGWJ', 'modeS': '3C5EEA', 'model': 'Airbus A319'}, 'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}}, {'departure': {'airport': {'icao': 'KSDF', 'iata': 'SDF', 'name': 'Louisville', 'countryCode': 'us', 'timeZone': 'America/Kentucky/Louisville'}, 'scheduledTime': {'utc': '2026-02-24 09:37Z', 'local': '2026-02-24 04:37-05:00'}, 'revisedTime': {'utc': '2026-02-24 10:30Z', 'local': '2026-02-24 05:30-05:00'}, 'runwayTime': {'utc': '2026-02-24 10:30Z', 'local': '2026-02-24 05:30-05:00'}, 'runway': '17R', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 17:08Z', 'local': '2026-02-24 18:08+01:00'}, 'quality': ['Basic']}, 'number': '5X 213', 'callSign': 'UPS213', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': True, 'aircraft': {'reg': 'N610UP', 'modeS': 'A7F08E', 'model': 'Boeing 747'}, 'airline': {'name': 'UPS', 'iata': '5X', 'icao': 'UPS'}}, {'departure': {'airport': {'icao': 'HEGN', 'iata': 'HRG', 'name': 'Hurghada', 'countryCode': 'eg', 'timeZone': 'Africa/Cairo'}, 'scheduledTime': {'utc': '2026-02-24 11:50Z', 'local': '2026-02-24 13:50+02:00'}, 'terminal': '2', 'quality': ['Basic']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 17:10Z', 'local': '2026-02-24 18:10+01:00'}, 'revisedTime': {'utc': '2026-02-24 17:25Z', 'local': '2026-02-24 18:25+01:00'}, 'terminal': '1', 'baggageBelt': 'D', 'quality': ['Basic', 'Live']}, 'number': 'EW 981', 'callSign': 'EWG981', 'status': 'Delayed', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'D-AEEE', 'modeS': '3C54A5', 'model': 'Airbus A320'}, 'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}, 'location': {'pressureAltitude': {'meter': 10363.2, 'km': 10.36, 'mile': 6.44, 'nm': 5.6, 'feet': 34000.0}, 'altitude': {'meter': 10363.2, 'km': 10.36, 'mile': 6.44, 'nm': 5.6, 'feet': 34000.0}, 'pressure': {'hPa': 0.0, 'inHg': 0.0, 'mmHg': 0.0}, 'groundSpeed': {'kt': 358.0, 'kmPerHour': 663.0, 'miPerHour': 412.0, 'meterPerSecond': 184.0}, 'trueTrack': {'deg': 320.0, 'rad': 5.585053606381854}, 'vsiFpm': -448, 'reportedAtUtc': '2026-02-24 15:52Z', 'lat': 44.17956, 'lon': 16.233347}}, {'departure': {'airport': {'icao': 'EDDB', 'iata': 'BER', 'name': 'Berlin', 'countryCode': 'de', 'timeZone': 'Europe/Berlin'}, 'scheduledTime': {'utc': '2026-02-24 16:30Z', 'local': '2026-02-24 17:30+01:00'}, 'revisedTime': {'utc': '2026-02-24 16:30Z', 'local': '2026-02-24 17:30+01:00'}, 'terminal': '1', 'checkInDesk': '323-326', 'gate': 'B01', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 17:35Z', 'local': '2026-02-24 18:35+01:00'}, 'revisedTime': {'utc': '2026-02-24 17:35Z', 'local': '2026-02-24 18:35+01:00'}, 'terminal': '1', 'baggageBelt': 'B', 'quality': ['Basic', 'Live']}, 'number': 'EW 8070', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'D-AEWS', 'modeS': '3C56F3', 'model': 'Airbus A320'}, 'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}}, {'departure': {'airport': {'icao': 'KMEM', 'iata': 'MEM', 'name': 'Memphis', 'countryCode': 'us', 'timeZone': 'America/Chicago'}, 'scheduledTime': {'utc': '2026-02-24 09:33Z', 'local': '2026-02-24 03:33-06:00'}, 'revisedTime': {'utc': '2026-02-24 10:05Z', 'local': '2026-02-24 04:05-06:00'}, 'runwayTime': {'utc': '2026-02-24 10:05Z', 'local': '2026-02-24 04:05-06:00'}, 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 17:51Z', 'local': '2026-02-24 18:51+01:00'}, 'quality': ['Basic']}, 'number': 'FX 4', 'callSign': 'FDX4', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': True, 'aircraft': {'reg': 'N862FD', 'modeS': 'ABD6C6', 'model': 'Boeing 777-200'}, 'airline': {'name': 'FedEx - Federal Express', 'iata': 'FX', 'icao': 'FDX'}}, {'departure': {'airport': {'icao': 'EDDM', 'iata': 'MUC', 'name': 'Munich', 'countryCode': 'de', 'timeZone': 'Europe/Berlin'}, 'scheduledTime': {'utc': '2026-02-24 16:50Z', 'local': '2026-02-24 17:50+01:00'}, 'revisedTime': {'utc': '2026-02-24 16:50Z', 'local': '2026-02-24 17:50+01:00'}, 'terminal': '2', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 17:55Z', 'local': '2026-02-24 18:55+01:00'}, 'revisedTime': {'utc': '2026-02-24 17:55Z', 'local': '2026-02-24 18:55+01:00'}, 'terminal': '1', 'baggageBelt': 'C', 'quality': ['Basic', 'Live']}, 'number': 'LH 1986', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320'}, 'airline': {'name': 'Lufthansa', 'iata': 'LH', 'icao': 'DLH'}}, {'departure': {'airport': {'icao': 'LEMG', 'iata': 'AGP', 'name': 'Málaga', 'countryCode': 'es', 'timeZone': 'Europe/Madrid'}, 'scheduledTime': {'utc': '2026-02-24 14:55Z', 'local': '2026-02-24 15:55+01:00'}, 'revisedTime': {'utc': '2026-02-24 14:52Z', 'local': '2026-02-24 15:52+01:00'}, 'runwayTime': {'utc': '2026-02-24 15:10Z', 'local': '2026-02-24 16:10+01:00'}, 'terminal': 'PAX', 'checkInDesk': '363-370', 'gate': 'D51', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 18:00Z', 'local': '2026-02-24 19:00+01:00'}, 'revisedTime': {'utc': '2026-02-24 18:00Z', 'local': '2026-02-24 19:00+01:00'}, 'terminal': '2', 'baggageBelt': 'B', 'quality': ['Basic', 'Live']}, 'number': 'FR 2307', 'callSign': 'RYR90ZG', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'EI-ILJ', 'modeS': '4CAFF7', 'model': 'Boeing 737'}, 'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}, 'location': {'pressureAltitude': {'meter': 10972.8, 'km': 10.97, 'mile': 6.82, 'nm': 5.92, 'feet': 36000.0}, 'altitude': {'meter': 10972.8, 'km': 10.97, 'mile': 6.82, 'nm': 5.92, 'feet': 36000.0}, 'pressure': {'hPa': 0.0, 'inHg': 0.0, 'mmHg': 0.0}, 'groundSpeed': {'kt': 479.0, 'kmPerHour': 887.0, 'miPerHour': 551.0, 'meterPerSecond': 246.0}, 'trueTrack': {'deg': 24.0, 'rad': 0.41887902047863906}, 'vsiFpm': -64, 'reportedAtUtc': '2026-02-24 15:52Z', 'lat': 41.257294, 'lon': -3.074736}}, {'departure': {'airport': {'icao': 'LEPA', 'iata': 'PMI', 'name': 'Palma De Mallorca', 'countryCode': 'es', 'timeZone': 'Europe/Madrid'}, 'scheduledTime': {'utc': '2026-02-24 15:45Z', 'local': '2026-02-24 16:45+01:00'}, 'revisedTime': {'utc': '2026-02-24 15:45Z', 'local': '2026-02-24 16:45+01:00'}, 'terminal': 'N', 'checkInDesk': '305-307', 'gate': 'C40', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 18:05Z', 'local': '2026-02-24 19:05+01:00'}, 'revisedTime': {'utc': '2026-02-24 18:05Z', 'local': '2026-02-24 19:05+01:00'}, 'terminal': '1', 'baggageBelt': 'B', 'quality': ['Basic', 'Live']}, 'number': 'EW 583', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A319'}, 'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}}, {'departure': {'airport': {'icao': 'LATI', 'iata': 'TIA', 'name': 'Tirana', 'countryCode': 'al', 'timeZone': 'Europe/Tirane'}, 'scheduledTime': {'utc': '2026-02-24 15:30Z', 'local': '2026-02-24 16:30+01:00'}, 'quality': ['Basic']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 18:20Z', 'local': '2026-02-24 19:20+01:00'}, 'revisedTime': {'utc': '2026-02-24 18:20Z', 'local': '2026-02-24 19:20+01:00'}, 'baggageBelt': 'D', 'quality': ['Basic', 'Live']}, 'number': 'W4 5121', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A321'}, 'airline': {'name': 'Wizz Air Malta', 'iata': 'W4', 'icao': 'WMT'}}, {'departure': {'airport': {'icao': 'LEMG', 'iata': 'AGP', 'name': 'Málaga', 'countryCode': 'es', 'timeZone': 'Europe/Madrid'}, 'scheduledTime': {'utc': '2026-02-24 15:50Z', 'local': '2026-02-24 16:50+01:00'}, 'revisedTime': {'utc': '2026-02-24 15:50Z', 'local': '2026-02-24 16:50+01:00'}, 'terminal': 'PAX', 'checkInDesk': '322-323', 'gate': 'D42', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 18:40Z', 'local': '2026-02-24 19:40+01:00'}, 'revisedTime': {'utc': '2026-02-24 18:40Z', 'local': '2026-02-24 19:40+01:00'}, 'terminal': '1', 'baggageBelt': 'C', 'quality': ['Basic', 'Live']}, 'number': 'EW 535', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320 NEO'}, 'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}}, {'departure': {'airport': {'icao': 'LYNI', 'iata': 'INI', 'name': 'Niš', 'countryCode': 'rs', 'timeZone': 'Europe/Belgrade'}, 'scheduledTime': {'utc': '2026-02-24 16:45Z', 'local': '2026-02-24 17:45+01:00'}, 'quality': ['Basic']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 19:05Z', 'local': '2026-02-24 20:05+01:00'}, 'revisedTime': {'utc': '2026-02-24 19:05Z', 'local': '2026-02-24 20:05+01:00'}, 'baggageBelt': 'D', 'quality': ['Basic', 'Live']}, 'number': 'JU 1298', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A319'}, 'airline': {'name': 'Air Serbia', 'iata': 'JU', 'icao': 'ASL'}}, {'departure': {'airport': {'icao': 'EGSS', 'iata': 'STN', 'name': 'London', 'countryCode': 'gb', 'timeZone': 'Europe/London'}, 'scheduledTime': {'utc': '2026-02-24 18:05Z', 'local': '2026-02-24 18:05+00:00'}, 'revisedTime': {'utc': '2026-02-24 18:05Z', 'local': '2026-02-24 18:05+00:00'}, 'terminal': '1', 'gate': '42', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 19:25Z', 'local': '2026-02-24 20:25+01:00'}, 'revisedTime': {'utc': '2026-02-24 19:25Z', 'local': '2026-02-24 20:25+01:00'}, 'terminal': '2', 'baggageBelt': 'D', 'quality': ['Basic', 'Live']}, 'number': 'FR 2814', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Boeing 737'}, 'airline': {'name': 'Ryanair', 'iata': 'FR', 'icao': 'RYR'}}, {'departure': {'airport': {'icao': 'GCRR', 'iata': 'ACE', 'name': 'Lanzarote Island', 'countryCode': 'es', 'timeZone': 'Atlantic/Canary'}, 'scheduledTime': {'utc': '2026-02-24 15:15Z', 'local': '2026-02-24 15:15+00:00'}, 'revisedTime': {'utc': '2026-02-24 15:15Z', 'local': '2026-02-24 15:15+00:00'}, 'terminal': '1', 'checkInDesk': '11-12', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 19:30Z', 'local': '2026-02-24 20:30+01:00'}, 'revisedTime': {'utc': '2026-02-24 19:30Z', 'local': '2026-02-24 20:30+01:00'}, 'terminal': '1', 'baggageBelt': 'C', 'quality': ['Basic', 'Live']}, 'number': 'EW 261', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'model': 'Airbus A320'}, 'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}}, {'departure': {'airport': {'icao': 'EDDB', 'iata': 'BER', 'name': 'Berlin', 'countryCode': 'de', 'timeZone': 'Europe/Berlin'}, 'scheduledTime': {'utc': '2026-02-24 19:05Z', 'local': '2026-02-24 20:05+01:00'}, 'revisedTime': {'utc': '2026-02-24 19:05Z', 'local': '2026-02-24 20:05+01:00'}, 'terminal': '1', 'checkInDesk': '323-326', 'quality': ['Basic', 'Live']}, 'arrival': {'scheduledTime': {'utc': '2026-02-24 20:10Z', 'local': '2026-02-24 21:10+01:00'}, 'revisedTime': {'utc': '2026-02-24 20:10Z', 'local': '2026-02-24 21:10+01:00'}, 'terminal': '1', 'baggageBelt': 'C', 'quality': ['Basic', 'Live']}, 'number': 'EW 15', 'status': 'Expected', 'codeshareStatus': 'IsOperator', 'isCargo': False, 'aircraft': {'reg': 'D-AGWG', 'modeS': '3C5EE7', 'model': 'Airbus A320'}, 'airline': {'name': 'Eurowings', 'iata': 'EW', 'icao': 'EWG'}}, {'departure': {'airport': {'icao': 'LSZH', 'iata': 'ZRH', 'name': 'Zurich', 'countryCode': 'ch',

In [31]:
import pandas as pd
import requests

# Example: list of airport IATA codes for your cities
iata_codes = ["BER", "CGN", "HAM"]  # Berlin, Cologne, Hamburg

# Store all arrivals in a single DataFrame
all_arrivals = []

for iata_code in iata_codes:
    url_arrivals = f"https://aerodatabox.p.rapidapi.com/flights/airports/iata/{iata_code}"
    querystring_arrivals = {
        "offsetMinutes": -120,
        "durationMinutes": 720,
        "withLeg": True,
        "direction": "Arrival",
        "withLocation": True
    }

    # Make the API request
    arrivals_response = requests.get(url_arrivals, headers=headers, params=querystring_arrivals)
    arrivals_data = arrivals_response.json()
    
    # Check if arrivals exist
    if "arrivals" in arrivals_data:
        arrivals_df = pd.json_normalize(
            arrivals_data['arrivals'],
            sep='_',
            meta=[
                ['flightNumber'],
                ['airline','name'],
                ['departure','airport','iata'],
                ['departure','airport','name'],
                ['departure','scheduledTimeLocal'],
                ['arrival','airport','icao'],
                ['arrival','airport','iata'],
                ['arrival','airport','name'],
                ['arrival','airport','location','lat'],
                ['arrival','airport','location','lon'],
                ['arrival','scheduledTimeLocal'],
                ['aircraft','model'],
                ['location','lat'],
                ['location','lon']
            ],
            errors='ignore'
        )

        # Rename columns for clarity
        arrivals_df = arrivals_df.rename(columns={
            'airline_name': 'airline_name',
            'departure_airport_iata': 'departure_airport_iata',
            'departure_airport_name': 'departure_airport_name',
            'departure_scheduledTimeLocal': 'departure_scheduledTimeLocal',
            'arrival_airport_icao': 'arrival_airport_icao',
            'arrival_airport_iata': 'arrival_airport_iata',
            'arrival_airport_name': 'arrival_airport_name',
            'arrival_airport_location_lat': 'arrival_airport_lat',
            'arrival_airport_location_lon': 'arrival_airport_lon',
            'arrival_scheduledTimeLocal': 'arrival_scheduledTimeLocal',
            'aircraft_model': 'aircraft_model',
            'location_lat': 'location_lat',
            'location_lon': 'location_lon'
        })

        # Optional: filter only useful columns
        useful_columns = [
            'flightNumber',
            'airline_name',
            'departure_airport_iata',
            'departure_airport_name',
            'departure_scheduledTimeLocal',
            'arrival_airport_icao',
            'arrival_airport_iata',
            'arrival_airport_name',
            'arrival_airport_lat',
            'arrival_airport_lon',
            'arrival_scheduledTimeLocal',
            'aircraft_model'
        ]
        arrivals_df = arrivals_df[[col for col in useful_columns if col in arrivals_df.columns]]

        # Append to main list
        all_arrivals.append(arrivals_df)

# Combine all arrivals into a single DataFrame
final_arrivals_df = pd.concat(all_arrivals, ignore_index=True)
print(final_arrivals_df)

        airline_name departure_airport_iata  \
0            British                    LHR
1             Condor                    FRA
2            Vueling                    BCN
3        Air Austral                    CDG
4    Delta Air Lines                    CDG
..               ...                    ...
266        Eurowings                    MUC
267        Eurowings                    SPC
268        Lufthansa                    FRA
269        Lufthansa                    MUC
270           Iberia                    MAD

                    departure_airport_name               aircraft_model
0                                   London              Airbus A320 NEO
1                        Frankfurt-am-Main                  Airbus A320
2                                Barcelona                  Airbus A320
3                                    Paris                  Airbus A320
4                                    Paris                  Airbus A320
..                                     ...                          ...
266                                 Munich              Airbus A319-100
267  Sta Cruz de la Palma, La Palma Island  Airbus A320-200 (sharklets)
268                      Frankfurt-am-Main  Airbus A320-200 (sharklets)
269                                 Munich  Airbus A320-200 (sharklets)
270                                 Madrid          Airbus A320-200 NEO

[271 rows x 4 columns]

In [27]:
final_arrivals_df.head()

,airline_name,departure_airport_iata,departure_airport_name,aircraft_model
0,AZAL Azerbaijan,GYD,Baku,Airbus A319
1,EasyJet Europe,LIN,Milan,Airbus A320
2,easyJet,LIN,Milan,Airbus A320
3,Ryanair,DUB,Dublin,Boeing 737-800
4,Vueling,BCN,Barcelona,Airbus A320 NEO

In [36]:
import requests
import pandas as pd
import os

# Your RapidAPI key
headers = {
    "X-RapidAPI-Key": os.getenv("FlightsAPI"),
    "X-RapidAPI-Host": "aerodatabox.p.rapidapi.com"
}

def get_airports_by_city(lat, lon, radius_km=50):
    """
    Returns a DataFrame of airports near a city, with important info like ICAO/IATA and coordinates.
    """
    url = f"https://aerodatabox.p.rapidapi.com/airports/search/location/{lat}/{lon}/km/{radius_km}/16"
    querystring = {"withFlightInfoOnly": "true"}

    response = requests.get(url, headers=headers, params=querystring)
    response.raise_for_status()
    
    data = response.json()
    
    # Check if 'items' exists
    if "items" in data and data["items"]:
        # Normalize JSON into DataFrame
        airport_df = pd.json_normalize(
            data['items'],
            sep='.'
        )
        
        # Keep only desired columns
        useful_columns = [
            'icao',
            'iata',
            'name',
            'shortName',
            'municipalityName',
            'countryCode',
            'timeZone',
            'location.lat',
            'location.lon'
        ]
        airport_df = airport_df[[col for col in useful_columns if col in airport_df.columns]]
        return airport_df
    else:
        # Return empty DataFrame with columns if no airports found
        return pd.DataFrame(columns=[
            'icao',
            'iata',
            'name',
            'shortName',
            'municipalityName',
            'countryCode',
            'timeZone',
            'location.lat',
            'location.lon'
        ])

# Example: get airports near Berlin, Cologne, Munich
city_coords = {
    "Berlin": (52.5200, 13.4050),
    "Cologne": (50.9364, 6.9528),
    "Hamburg": (53.5500, 10.0000)
}

all_airports = pd.DataFrame()

for city, (lat, lon) in city_coords.items():
    df = get_airports_by_city(lat, lon)
    df['city'] = city  # add city column
    all_airports = pd.concat([all_airports, df], ignore_index=True)

print(all_airports)

   icao iata                name    shortName municipalityName countryCode  \
0  EDDT  TXL       Berlin -Tegel       -Tegel           Berlin          DE
1  EDDB  BER  Berlin Brandenburg  Brandenburg           Berlin          DE
2  EDDK  CGN        Cologne Bonn         Bonn          Cologne          DE
3  EDDL  DUS          Düsseldorf   Düsseldorf       Düsseldorf          DE
4  EDDH  HAM             Hamburg      Hamburg          Hamburg          DE

        timeZone  location.lat  location.lon     city
0  Europe/Berlin      52.55970     13.287699   Berlin
1  Europe/Berlin      52.35139     13.493889   Berlin
2  Europe/Berlin      50.86590      7.142739  Cologne
3  Europe/Berlin      51.28950      6.766779  Cologne
4  Europe/Berlin      53.63040      9.988229  Hamburg

In [37]:
all_airports.head()

,icao,iata,name,shortName,municipalityName,countryCode,timeZone,location.lat,location.lon,city
0,EDDT,TXL,Berlin -Tegel,-Tegel,Berlin,DE,Europe/Berlin,52.55970,13.287699,Berlin
1,EDDB,BER,Berlin Brandenburg,Brandenburg,Berlin,DE,Europe/Berlin,52.35139,13.493889,Berlin
2,EDDK,CGN,Cologne Bonn,Bonn,Cologne,DE,Europe/Berlin,50.86590,7.142739,Cologne
3,EDDL,DUS,Düsseldorf,Düsseldorf,Düsseldorf,DE,Europe/Berlin,51.28950,6.766779,Cologne
4,EDDH,HAM,Hamburg,Hamburg,Hamburg,DE,Europe/Berlin,53.63040,9.988229,Hamburg

In [34]:
from sqlalchemy import create_engine
import os

schema = "sql_workshop"          
host = "127.0.0.1"
user = "root"
password = os.getenv("MySQLPassword")
port = 3306

engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}:{port}/{schema}"
)

In [93]:
all_airports.to_sql(
    name="flights",
    con=engine,
    if_exists="append",
    index=False
)

5

In [38]:
#Again exporting data to GCP follow steps like in weather and try to trouble shoot from experience

# 1. Prepare your DataFrame columns to match the SQL schema exactly
# Note: Pay close attention to the capitalization!
flights_to_sql = all_airports.rename(columns={
    'location.lat': 'location_lat',
    'location.lon': 'location_lon',
    'city': 'city' # already matches your loop, but good to be sure
})

# 2. Add the city_id column
# If you haven't merged city_ids yet, we can set them to None for now
if 'city_id' not in flights_to_sql.columns:
    flights_to_sql['city_id'] = None

# 3. Clear any "stuck" transactions on the cloud engine
from sqlalchemy import text
with engine.connect() as conn:
    conn.rollback()

# 4. Export to GCP
try:
    flights_to_sql.to_sql(
        name="flights", 
        con=engine, 
        if_exists="append", # Appending keeps your auto_increment flight_id and Foreign Key
        index=False
    )
    print(f"Successfully exported {len(flights_to_sql)} flight locations to GCP!")
except Exception as e:
    print(f"Error during export: {e}")

Successfully exported 5 flight locations to GCP!

In [44]:
def main_work_flow_weather():   
    engine = create_engine_cloud()
    cities = get_cities(engine)
    weather_df = get_weather_dataframe(cities)
    message= push_weather_to_cloud(weather_df, engine)
    return message

In [45]:
main_work_flow_weather()

'Cloud Update Successful!'